---
title: "Homework 2"
author: "Zhaoxia Yu"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Due on \textcolor{red}{Monday, May 1st 2023}. R Code should be included as appendices. 
- \textcolor{red}{Problem 1}: Choose a $3-by-3$ covariance matrix with non-zero covariances. Also choose a sample size $n$. Simulate 1,000 data sets from a trivariate normal distribution. 
  0. Hints: 
    - Hint 1: the R library MASS provides a function to generate a random sample from a multivariate normal distribution. 
    - Hint 2: Make sure that the covariance matrix you choose is positive definite.  You can compute the eigenvalues by the "eigen" function in R and and check whether all the eigenvalues are positive. 
  1. Try to make sense of the covariance matrix by examining the pairwise scatter plots using the data you simulate. 
  2. During the simulation, you will generate 1,000 Wishart distributed random matrices. Calculate the trace for each of them. Explain what distribution the traces should follow and examine their histogram.
  
- \textcolor{red}{Problem 2}: Find a good data example to conduct a two-sample Hotelling's $T^2$ test. Do not use the data example discussed in this course. Please (1) include visualizations as exploratory methods and (2) make conclusion in the context of the data example.  

- R Code should be included as appendices. 